alias: "Clear vacation mode alert"
trigger:
  - platform: state
    entity_id: 'input_boolean.vacation_mode'
condition:
  - condition: state
    entity_id: 'input_boolean.vacation_mode_alert'
    state: 'on'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.vacation_mode_alert
