homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customizations

frontend:
config:

http:
  base_url: assist.deadlypenguin.com:80
  api_password: !secret http_pass

updater:
#discovery:
hassio:
history:
logbook:
tts:
  - platform: google
cloud:
mqtt:

zwave:
  usb_path: /dev/ttyACM0

automation: !include_dir_list automations
#camera: !include_dir_merge_list cameras
camera: !include cameras.yaml
cover: !include_dir_merge_list covers
device_tracker: !include device_tracker.yaml
group: !include_dir_named groups
media_player: !include_dir_merge_list media_players
notify: !include notify.yaml
octoprint: !include octoprint.yaml
script: !include_dir_named scripts
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
