homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customizations

frontend:
  themes: !include_dir_named themes
#alexa:
config:
recorder:
  db_url: !secret mariadb_path

http:
  base_url: assist.deadlypenguin.com:80
  api_password: !secret http_pass

sun:
updater:
#discovery:
hassio:
history:
logbook:
  exclude:
    entities:
      - input_number.timestamp_beth
      - input_number.timestamp_pcon
      - automation.set_last_seen_timestamp_for_beth
      - automation.set_last_seen_timestamp_for_pcon
      - automation.update_the_gone_time
tts:
  - platform: google_translate
    service_name: google_say
mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_pass

zwave:
  usb_path: /dev/ttyACM0

system_health:
owntracks:
map:
lovelace:
  mode: yaml
zone: !include zones.yaml

alert: !include_dir_merge_named alerts
automation: !include_dir_list automations
binary_sensor: !include_dir_merge_list binary_sensors
camera: !include cameras.yaml
#cast: !include cast.yaml
cover: !include covers.yaml
device_tracker: !include device_tracker.yaml
group: !include_dir_named groups
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
intent_script: !include_dir_merge_named intent_scripts
media_player: !include_dir_merge_list media_players
notify: !include notify.yaml
person: !include people.yaml
roku: !include roku.yaml
scene: !include_dir_merge_list scenes
script: !include_dir_named scripts
shell_command: !include shell_commands.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
tplink: !include tplink.yaml
weather: !include weather.yaml

hangouts:
  intents: !include_dir_merge_named hangouts
google_assistant: !include google_assistant.yaml

climate:
  - platform: zwave
