- platform: template
  covers:
    garage_door_main:
      friendly_name: "Main Garage Door"
      value_template: "{{ is_state('binary_sensor.garage_door_main_sensor', 'on') }}"
      open_cover:
        service: script.no_op
      close_cover:
        service: script.no_op
      stop_cover:
        service: script.no_op
      icon_template: >-
        {% if is_state('binary_sensor.garage_door_main_sensor', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}
    garage_door_secondary:
      friendly_name: "Secondary Garage Door"
      value_template: "{{ is_state('binary_sensor.garage_door_secondary_sensor', 'on') }}"
      open_cover:
        service: script.no_op
      close_cover:
        service: script.no_op
      stop_cover:
        service: script.no_op
      icon_template: >-
        {% if is_state('binary_sensor.garage_door_secondary_sensor', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}
