- platform: unifi
  username: !secret unifi_user
  password: !secret unifi_pass
  host: !secret unifi_host
  port: !secret unifi_port
  verify_ssl: false
  track_new_devices: no
  monitored_conditions:
    - essid
    - hostname
    - idletime
    - ap_mac
    - last_seen
  interval_seconds: 60
