title: Home
resources:
        - url: /local/mini-graph-card/mini-graph-card.js?v=0.0.6
          type: module
views:
        - title: Home 
          id: home
          icon: mdi:home
          cards:
                  - id: peoplehome
                    type: entity-filter
                    entities:
                            - device_tracker.pcon
                            - device_tracker.beth
                    state_filter:
                            - 'home'
                            - 'not_home'
                    card:
                            type: glance
                            title: People
                  - id: christmas
                    type: conditional
                    conditions:
                            - entity: input_boolean.christmas_setup
                              state: "on"
                    card:
                            type: entities
                            title: Christmas
                            show_header_toggle: false
                            entities:
                                    - entity: scene.downstairs_christmas
                                      name: Make it Christmas
                                      icon: mdi:snowman
                                    - entity: switch.tplink1
                                      name: Christmas Tree
                                      icon: mdi:pine-tree
                                    - entity: switch.tplink2
                                      name: Railing
                                      icon: mdi:track-light
                                    - entity: switch.front_porch_switch
                                      name: Star and Laser
                                      icon: mdi:star-four-points
                                    - entity: scene.downstairs_normal
                                      name: Goodnight
                                      icon: mdi:weather-night
                  - id: downstairs_switches
                    type: conditional
                    conditions:
                            - entity: input_boolean.christmas_setup
                              state: "off"
                    card:
                            type: entities
                            title: Downstairs 
                            show_header_toggle: false
                            entities:
                                    - entity: switch.tplink1
                                      name: Living Room
                                      icon: mdi:sofa
                                    - entity: switch.tplink2
                                      name: Foyer
                                      icon: mdi:track-light
                                    - entity: switch.front_porch_switch
                                      name: Front Porch
                                      icon: mdi:flower
                                    - entity: scene.downstairs_normal
                                      name: Goodnight
                                      icon: mdi:weather-night

        - title: Server
          id: server
          icon: mdi:server
          cards:
                  - id: test
                    type: entities
                    title: Test
                    entities:
                            - entity: automation.holiday_lights_off__non_vacation
                              name: Holiday Lights Off - Non Vacation
                            - entity: automation.holiday_lights_off__vacation
                              name: Holiday Lights Off - Vacation
        - title: Temps
          id: temps
          icon: mdi:thermometer-lines
          cards:
                  - id: freezer
                    type: "custom:mini-graph-card"
                    entity: sensor.freezer
                    height: 100
                    line_width: 4
                    font_size: 75
                    color: '#3498db'
                  - id: thermostats
                    type: horizontal-stack
                    cards:
                        - type: "custom:mini-graph-card"
                          entity: sensor.upstairs_thermostat_temperature
                          height: 100
                          line_width: 4
                          font_size: 75
                          color: '#3498db'
                        - type: "custom:mini-graph-card"
                          entity: sensor.downstairs_thermostat_temperature
                          height: 100
                          line_width: 4
                          font_size: 75
                          color: '#3498db'

        - title: Holidays
          id: holidays
          icon: mdi:calendar-search
          cards:
                 - id: holiday_setup
                   type: entities
                   title: Holiday Setup
                   show_header_toggle: false
                   entities:
                           - entity: input_boolean.christmas_setup
                             name: Is Christmas setup?
                 - id: vacation
                   type: entities
                   title: Vacation
                   show_header_toggle: false
                   entities:
                           - entity: input_boolean.vacation_mode
                             name: Vacation Mode
                           - entity: input_boolean.vacation_mode_alert
                             name: Vacation Mode alert sent
                 - id: automation
                   type: entities
                   title: Automation
                   show_header_toggle: false
                   entities:
                           - entity: automation.christmas_lights
                           - entity: automation.holiday_lights_off__non_vacation
                           - entity: automation.holiday_lights_off__vacation
                           - entity: automation.clear_vacation_mode_alert
                           - entity: automation.remind_vacation_mode
                           - entity: automation.remind_turn_off_vacation_mode
                           - entity: automation.turn_off_scooter_warmer_at_night
                           - entity: automation.turn_off_scooter_warmer_when_everyone_leaves
                           - entity: automation.notify_if_the_left_garage_door_has_been_open_too_long
                           - entity: automation.notify_if_the_left_garage_door_has_been_opened_in_the_middle_of_the_night
                           - entity: automation.notify_if_the_right_garage_door_has_been_open_too_long
                           - entity: automation.notify_if_the_right_garage_door_has_been_opened_in_the_middle_of_the_night
