name: Home
views:
  - !include lovelace/view_default.yaml
  - !include lovelace/view_media.yaml
  - !include lovelace/view_cameras.yaml
resources:
  - url: /local/lovelace/weather-card.js
    type: module
  - url: /local/lovelace/vertical-stack-in-card.js?v=0.1.2
    type: js
  - url: /local/lovelace/dual-thermostat.js?v=1
    type: js
  - url: /local/lovelace/camera-card.js
    type: module
