alias: "Notify if the secondary garage door has been opened in the middle of the night"
trigger:
  - platform: state
    entity_id: cover.garage_door_secondary 
    to: 'open'
condition:
  condition: or
  conditions:
    - condition: time
      after: '22:00:00'
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
    - condition: time
      before: '05:00:00'
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
action:
  - service: notify.pushover
    data:
      message: "Secondary garage door open"
      title: "Garage door"
      data:
        priority: 2
        sound: "persistent"
        expire: 10800
        retry: 30
