alias: "Notify if the left garage door has been open too long"
trigger:
  - platform: state
    entity_id: cover.garage_left
    to: 'open'
    for:
      hours: 2
action:
  - service: notify.pushover
    data:
      message: "Left garage door is still open"
      title: "Garage door"
