alias: "Notify if the secondary garage door has been open too long"
trigger:
  - platform: state
    entity_id: cover.garage_door_secondary
    to: 'open'
    for:
      hours: 2
action:
  - service: notify.pushover
    data:
      message: "Secondary garage door is still open"
      title: "Garage door"
