alias: "Printer offline"
trigger: 
  - platform: state
    entity_id: sensor.laser_printer
    to: 'Offline'
    for:
      minutes: 30
action:
  - service: notify.pushover
    data:
      message: "Printer offline"
      title: "Home Assistant"
