alias: "Downstairs Thermostat Changed"
trigger:
  platform: state
  entity_id: sensor.thermostat_downstairs_temp
action:
  - service: notify.pushover
    data:
      message: "Downstairs thermostat changed to {{ states('sensor.thermostat_upstairs_temp') }}"
      title: "Thermostat Changed"
