alias: "Alert when pcon is home"
trigger:
        platform: state
        entity_id: device_tracker.pcon
        from: 'not_home'
        to: 'home'
action:
        service: notify.pushover
        data:
                message: "pcon is home"
                title: "Home"
