alias: "Sunlow Notification"
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: .75
action:
  - service: notify.hangouts_pcon
    data:
      message: 'The sun is getting real low big guy'
