alias: "Remind turn off vacation mode"
trigger:
  - platform: time
    minutes: '/10'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'input_boolean.vacation_mode'
      state: 'on'
    - condition: state
      entity_id: 'input_boolean.vacation_mode_alert'
      state: 'off'
    - condition: or
      conditions:
         - condition: numeric_state
           entity_id: sensor.seen_pcon
           below: 1
         - condition: numeric_state
           entity_id: sensor.seen_beth
           below: 1
action:
  - service: notify.hangouts_pcon
    data:
      message: 'Did you forget to disable vacation mode?'
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.vacation_mode_alert
