alias: "Remind vacation mode"
trigger:
  - platform: time_pattern
    minutes: '/10'
condition:
  - condition: state
    entity_id: 'input_boolean.vacation_mode'
    state: 'off'
  - condition: state
    entity_id: 'input_boolean.vacation_mode_alert'
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.pcon_gone
    above: 18
  - condition: numeric_state
    entity_id: sensor.beth_gone
    above: 18
action:
  - service: notify.hangouts_pcon
    data:
      message: 'Did you forget to enable vacation mode?'
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.vacation_mode_alert
