alias: 'Wake Dispatch Home'
trigger:
  platform: geo_location
  source: geo_json_events
  zone: zone.home_large
  event: enter
action:
  service: notify.pushover
  data_template:
    message: "{{ trigger.to_state.attributes.friendly_name }}"
  data:
    title: 'Wake Dispatch'
