- platform: rest
  name: 'Freezer'
  json_attributes:
          - last_checkin
          - state
  unit_of_measurement: "°F"
  value_template: "{{ value_json.state | round(2) }}"
  resource: !secret freezer_host
- platform: statistics
  name: freezer
  entity_id: sensor.freezer
  max_age:
          minutes: 30
- platform: template
  sensors:
    freezer_checkin:
      entity_id: sensor.freezer
      friendly_name: 'Freezer Last Check-in'
      unit_of_measurement: 'Minutes'
      value_template: "{{ ((as_timestamp(utcnow()) - states('input_number.timestamp_freezer') | float) / 60) | round(0) }}"
      icon_template: "mdi:alarm-check"
