- platform: rest
  name: 'Freezer'
  json_attributes:
          - last_checkin
          - state
  unit_of_measurement: "°F"
  value_template: "{{ value_json.state | round(2) }}"
  resource: !secret freezer_host
- platform: statistics
  name: freezer
  entity_id: sensor.freezer
  max_age:
          minutes: 30
