- platform: template
  sensors:
    seen_pcon:
      friendly_name: "Seen Patrick"
      unit_of_measurement: 'hours'
      value_template: >-
        {% if state_attr('device_tracker.pcon', 'last_seen') == None %}
           24
        {% else %}
           {{ ((as_timestamp(utcnow()) - state_attr('device_tracker.pcon', 'last_seen')) / 3600) | round (2) }}
        {% endif %}
    seen_beth:
      friendly_name: "Seen Beth"
      unit_of_measurement: 'hours'
      value_template: >-
        {% if state_attr('device_tracker.beth', 'last_seen') == None %}
           24
        {% else %}
           {{ ((as_timestamp(utcnow()) - state_attr('device_tracker.beth', 'last_seen')) / 3600) | round (2) }}
        {% endif %}
