- platform: template
  sensors:
    thermostat_upstairs_state:
      friendly_name: "State"
      value_template: >
        {% if states.climate.upstairs_thermostat_cooling_1 %}
          {{ states("climate.upstairs_thermostat_cooling_1") | capitalize }}
        {% else %}
          Loading
        {% endif %}
    thermostat_upstairs_temp:
      friendly_name: "Upstairs Set Temp"
      unit_of_measurement: '°F'
      value_template: >
        {% if is_state("climate.upstairs_thermostat_cooling_1", "heat") %}
          {{ state_attr("climate.upstairs_thermostat_heating_1", "temperature") }}
        {% else %}
          {{ state_attr("climate.upstairs_thermostat_cooling_1", "temperature") }}
        {% endif %}
