- platform: template
  sensors:
    thermostat_upstairs_state:
      friendly_name: "State"
      value_template: >
        {% if states.climate.upstairs_thermostat_cooling_1 %}
          {{ states.climate.upstairs_thermostat_cooling_1.attributes.operating_state }}
        {% else %}
          Loading
        {% endif %}
