- platform: wunderground
  api_key: !secret wunderground_api
  monitored_conditions:
    - alerts
    - heat_index_f
    - relative_humidity
    - temp_f
    - temp_high_record_f
    - temp_low_record_f
    - temp_high_avg_f
    - temp_low_avg_f
    - temp_high_1d_f
    - temp_low_1d_f
    - weather_1h
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n
