- platform: template
  sensors:
    garage_door_main_open:
      friendly_name: "Main garage door stuck"
      device_class: garage_door
      entity_id: binary_sensor.garage_door_main_sensor
      value_template: "{{ is_state('garage_door_main_sensor', 'on') }}"
      delay_on:
        hours: 2
    garage_door_secondary_open:
      friendly_name: "Secondary garage door stuck"
      device_class: garage_door
      entity_id: binary_sensor.garage_door_secondary_sensor
      value_template: "{{ is_state('garage_door_secondary_sensor', 'on') }}"
      delay_on:
        hours: 2
