alias: "Bennett's Room - On"
trigger:
  - platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.bennett_bedtime.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
action:
  - service: scene.turn_on
    entity_id: scene.bennett_s_room_on
