alias: "Turn off scooter warmer at night"
trigger:
  - platform: time
    at: '22:00:00'
condition:
    condition: state
    entity_id: switch.scooter
    state: 'on'
action:
  - service: script.turn_off_scooter_and_alert
