alias: "Turn off scooter warmer when everyone leaves"
trigger:
  - platform: state
    entity_id: group.all_devices
    to: 'not_home'
    for:
      minutes: 10
condition:
    condition: state
    entity_id: switch.scooter
    state: 'on'
action:
  - service: script.turn_off_scooter_and_alert
