- platform: mqtt
  name: "Garage Right"
  state_topic: "home-assistant/cover/garage/right/state"
  qos: 0
  retain: true
  state_open: "open"
  state_closed: "closed"
  optimistic: false
- platform: mqtt
  name: "Garage Left"
  state_topic: "home-assistant/cover/garage/left/state"
  qos: 0
  retain: true
  state_open: "open"
  state_closed: "closed"
  optimistic: false
