alias: "Holiday Lights Off - Vacation"
trigger:
  - platform: time 
    at: '07:00:00'
condition:
  condition: and
  conditions:
    - platform: state
      entity: input_boolean.vacation_mode
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.christmas_setup
          state: 'on'
action:
  - service: scene.turn_on
    entity_id: scene.downstairs_normal
  - service: notify.hangouts_pcon
    data:
      message: 'Goodnight, Goodnight, Holiday Lights'
